name: Release

on:
  release:
    types: [published]

jobs:
  add-artifacts-to-github-release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Zip extensions
        working-directory: apps/debugger-extension
        run: |
          pnpm zip
          pnpm zip:firefox

      - name: Submit to stores
        working-directory: apps/debugger-extension/.output
        run: gh release upload ${{github.event.release.tag_name}} *{chrome,firefox}.zip
        env:
          GH_TOKEN: ${{ github.token }}
